#!/usr/bin/env node
/**
 * Reads .env and writes assets/js/config.js for the static site.
 * Usage: node scripts/sync-env.js
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const envPath = path.join(root, ".env");
const outPath = path.join(root, "assets", "js", "config.js");

function parseEnv(text) {
    const out = {};
    text.split(/\r?\n/).forEach(function (line) {
        var trimmed = line.trim();
        if (!trimmed || trimmed.charAt(0) === "#") return;
        var i = trimmed.indexOf("=");
        if (i === -1) return;
        var key = trimmed.slice(0, i).trim();
        var val = trimmed.slice(i + 1).trim();
        if (
            (val.charAt(0) === '"' && val.charAt(val.length - 1) === '"') ||
            (val.charAt(0) === "'" && val.charAt(val.length - 1) === "'")
        ) {
            val = val.slice(1, -1);
        }
        out[key] = val;
    });
    return out;
}

if (!fs.existsSync(envPath)) {
    console.error("Missing .env — copy .env.example to .env and add WEB3FORMS_ACCESS_KEY");
    process.exit(1);
}

var env = parseEnv(fs.readFileSync(envPath, "utf8"));
var key = env.WEB3FORMS_ACCESS_KEY || "";

var js =
    "/* Generated by scripts/sync-env.js — do not edit by hand */\n" +
    "window.__ENV = {\n" +
    '  WEB3FORMS_ACCESS_KEY: "' +
    key.replace(/\\/g, "\\\\").replace(/"/g, '\\"') +
    '"\n' +
    "};\n";

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, js, "utf8");

if (key) {
    console.log("OK — config.js updated with Web3Forms key (" + key.slice(0, 8) + "…)");
} else {
    console.log("OK — config.js updated, but WEB3FORMS_ACCESS_KEY is still empty in .env");
}
